/**
 * Narrative content for the no-login demo workspace.
 *
 * IMPORTANT: no scores, snapshots or price metrics live here any more.
 * Prices, volumes, peer performance and volatility are persisted in the
 * `stock_snapshots` table; attention scores, classifications and explanations
 * are generated by the SnapshotEngine + AttentionEngine.
 * This file only carries the editorial "what happened" text for the timeline.
 */

const HOUR = 3600_000;
const ago = (hours: number) => new Date(Date.now() - hours * HOUR).toISOString();

export type DemoActivity = {
  id: string;
  ticker: string;
  occurredAt: string;
  category: string;
  sentiment: "positive" | "negative" | "neutral";
  headline: string;
  summary: string;
  source: string;
};

export const DEMO_WATCHLIST = {
  name: "Indian Large Cap",
  /** Simulated "last visit" marker for the Since You Were Away section. */
  lastSeenAt: ago(26),
};

export const DEMO_ACTIVITY: DemoActivity[] = [
  {
    id: "a1",
    ticker: "TCS",
    occurredAt: ago(3),
    category: "momentum",
    sentiment: "positive",
    headline: "TCS jumps on a large multi-year deal win",
    summary:
      "A $2.1B managed-services contract with a European bank was confirmed before market open. Volume ran multiples of its normal average, and the move held into the close instead of fading — a sign institutions were buying, not day traders.",
    source: "Exchange filing",
  },
  {
    id: "a2",
    ticker: "INFY",
    occurredAt: ago(6),
    category: "sector",
    sentiment: "positive",
    headline: "Infosys pulled higher as IT sector momentum builds",
    summary:
      "Infosys advanced without company-specific news. The whole IT index moved on the back of the TCS deal, so this is largely sector spillover. Intraday swings widened noticeably.",
    source: "PulseIQ signal",
  },
  {
    id: "a3",
    ticker: "RELIANCE",
    occurredAt: ago(11),
    category: "analyst",
    sentiment: "negative",
    headline: "Reliance downgraded on refining margin pressure",
    summary:
      "Two brokerages cut Reliance to hold, citing thinner refining spreads for the coming quarter. The stock lagged the energy index, so the weakness is company-specific rather than market-wide.",
    source: "Analyst note",
  },
  {
    id: "a4",
    ticker: "ICICIBANK",
    occurredAt: ago(19),
    category: "news",
    sentiment: "neutral",
    headline: "ICICI Bank drifts with the banking index",
    summary:
      "A small decline that mirrors the banking index almost exactly. No filing, no guidance change — this is index movement, not a company story.",
    source: "PulseIQ signal",
  },
  {
    id: "a5",
    ticker: "HDFCBANK",
    occurredAt: ago(31),
    category: "earnings",
    sentiment: "positive",
    headline: "HDFC Bank posts steady deposit growth",
    summary:
      "Quarterly deposits grew 4% sequentially, in line with expectations. The market reaction was muted with normal volume — confirmation of the existing story rather than new information.",
    source: "Quarterly update",
  },
  {
    id: "a6",
    ticker: "TCS",
    occurredAt: ago(44),
    category: "news",
    sentiment: "neutral",
    headline: "TCS scheduled a board meeting for the deal announcement",
    summary:
      "The filing that preceded the move. On its own it looked routine; in hindsight it was the first marker of the contract that repriced the stock.",
    source: "Exchange filing",
  },
  {
    id: "a7",
    ticker: "RELIANCE",
    occurredAt: ago(58),
    category: "news",
    sentiment: "neutral",
    headline: "Reliance retail arm opened 40 new stores",
    summary:
      "An expansion update with little price effect. Included so the timeline shows the full context leading into the downgrade two days later.",
    source: "Company release",
  },
];

/** Activity newest-first. */
export const DEMO_ACTIVITY_DESC = [...DEMO_ACTIVITY].sort(
  (a, b) => +new Date(b.occurredAt) - +new Date(a.occurredAt),
);

export const DEMO_SINCE_AWAY = DEMO_ACTIVITY_DESC.filter(
  (e) => +new Date(e.occurredAt) > +new Date(DEMO_WATCHLIST.lastSeenAt),
);

export function demoActivityFor(ticker: string) {
  return DEMO_ACTIVITY_DESC.filter((e) => e.ticker.toUpperCase() === ticker.toUpperCase());
}
